Enedis-OSS/chutney

kotlin-dsl/pom.xml
=> chore(): fix dsl javadoc generation

chutney/ui/src/app/modules/target/targets.routes.ts
=> fix(ui): Prevent title page modification when editing a target

chutney/ui/src/assets/i18n/en.json, chutney/ui/src/assets/i18n/fr.json
=> fix(ui): Fix jiraId wording in campaign edition interface

acceptance-tests/src/test/kotlin/com/chutneytesting/acceptance/AcceptanceTests.kt, chutney/server/src/main/java/com/chutneytesting/execution/infra/storage/ScenarioExecutionReportJpaRepository.java, chutney/server/src/main/java/com/chutneytesting/migration/domain/ExecutionReportMigrator.java, chutney/server/src/main/java/com/chutneytesting/scenario/infra/raw/ScenarioJpaRepository.java, example/pom.xml
=> fix(server): index execution for only activated scenarios

chutney/action-impl/src/main/java/com/chutneytesting/action/jakarta/JakartaConnectionFactory.java, chutney/action-impl/src/main/java/com/chutneytesting/action/jakarta/UncheckedJakartaException.java, chutney/action-impl/src/main/java/com/chutneytesting/action/jms/JmsConnectionFactory.java, chutney/action-impl/src/main/java/com/chutneytesting/action/jms/UncheckedJmsException.java, chutney/engine/src/main/java/com/chutneytesting/engine/domain/delegation/CannotDelegateException.java, chutney/engine/src/main/java/com/chutneytesting/engine/domain/execution/engine/evaluation/EvaluationException.java, chutney/engine/src/main/java/com/chutneytesting/engine/domain/execution/engine/evaluation/StepDataEvaluator.java, chutney/engine/src/main/java/com/chutneytesting/engine/infrastructure/delegation/HttpClient.java, chutney/environment/src/main/java/com/chutneytesting/environment/domain/Environment.java, chutney/environment/src/main/java/com/chutneytesting/environment/domain/EnvironmentService.java, chutney/environment/src/main/java/com/chutneytesting/environment/domain/exception/AlreadyExistingEnvironmentException.java, chutney/environment/src/main/java/com/chutneytesting/environment/domain/exception/AlreadyExistingTargetException.java, chutney/environment/src/main/java/com/chutneytesting/environment/domain/exception/CannotDeleteEnvironmentException.java, chutney/environment/src/main/java/com/chutneytesting/environment/domain/exception/EnvVariableNotFoundException.java, chutney/environment/src/main/java/com/chutneytesting/environment/domain/exception/EnvironmentNotFoundException.java, chutney/environment/src/main/java/com/chutneytesting/environment/domain/exception/InvalidEnvironmentNameException.java, chutney/environment/src/main/java/com/chutneytesting/environment/domain/exception/NoEnvironmentFoundException.java, chutney/environment/src/main/java/com/chutneytesting/environment/domain/exception/SingleEnvironmentException.java, chutney/environment/src/main/java/com/chutneytesting/environment/domain/exception/UnresolvedEnvironmentException.java, chutney/environment/src/main/java/com/chutneytesting/environment/infra/JsonFilesEnvironmentRepository.java, chutney/environment/src/test/java/com/chutneytesting/environment/api/environment/HttpEnvironmentApiTest.java, chutney/environment/src/test/java/com/chutneytesting/environment/api/target/TargetControllerTest.java, chutney/environment/src/test/java/com/chutneytesting/environment/api/variable/VariableControllerTest.java, chutney/server-core/src/main/java/com/chutneytesting/server/core/domain/scenario/AlreadyExistingScenarioException.java, chutney/server/src/test/java/com/chutneytesting/RestExceptionHandlerTest.java, kotlin-dsl/src/main/kotlin/com/chutneytesting/kotlin/util/HttpClient.kt
=> chore(): Delete message in exception constructors

chutney/ui/src/app/core/model/scenario/scenario-execution-report.model.ts, chutney/ui/src/app/core/model/scenario/step-execution-report.model.spec.ts, chutney/ui/src/app/core/model/scenario/step-execution-report.model.ts, chutney/ui/src/app/modules/scenarios/components/execution/detail/execution.component.ts
* Flatten one interation steps
=> Clean scenario execution report

acceptance-tests/src/test/kotlin/com/chutneytesting/acceptance/AcceptanceTests.kt, chutney/.docker/README.md, chutney/.docker/docker-compose-custom-config.yml, chutney/.docker/docker-compose-local-dev.yml, chutney/packaging/local-dev/pom.xml, docs/docs/installation/local_dev.md, example/.docker/README.md, example/.docker/demo/Dockerfile, example/.docker/dev-docker-compose-demo.yml, example/src/test/kotlin/com/chutneytesting/example/selenium/SeleniumTest.kt
=> fix: Docker link to new oss-enedis organisation

chutney/ui/src/app/core/components/login/login.component.html, chutney/ui/src/assets/i18n/en.json, chutney/ui/src/assets/i18n/fr.json
Use i18n assets for login component.
=> Clean login i18n

chutney/packaging/local-api-unsecure/src/main/resources/logback.xml, chutney/packaging/local-dev/src/main/resources/application.yml, chutney/packaging/local-dev/src/main/resources/logback.xml, docs/docs/index.md, example/.docker/demo/spring-config/application.yml, example/.docker/dev-docker-compose-demo.yml, example/.docker/supervision/grafana/datasources/datasources.yml, example/.docker/supervision/prometheus/prometheus.yml, example/.gitignore
=> Example demo : Add jwt configuration + clean

chutney/action-impl/src/main/java/com/chutneytesting/action/function/DateTimeFunctions.java, chutney/action-impl/src/main/java/com/chutneytesting/action/function/EscapeFunctions.java, chutney/action-impl/src/test/java/com/chutneytesting/action/function/DateTimeFunctionsTest.java, docs/docs/documentation/actions/micrometer.md, docs/docs/documentation/actions/ssh.md, docs/docs/documentation/functions/classpath.md, docs/docs/documentation/functions/datetime.md, docs/docs/documentation/functions/escape.md, docs/docs/documentation/functions/generate.md, docs/docs/documentation/functions/nullable.md
=> feat(action): Add URL encode/decode and duration between functions

chutney/action-impl/src/main/java/com/chutneytesting/action/assertion/JsonAssertAction.java, chutney/action-impl/src/main/java/com/chutneytesting/action/assertion/XmlAssertAction.java, chutney/action-impl/src/main/java/com/chutneytesting/action/assertion/placeholder/AfterDateAsserter.java, chutney/action-impl/src/main/java/com/chutneytesting/action/assertion/placeholder/BeforeDateAsserter.java, chutney/action-impl/src/main/java/com/chutneytesting/action/assertion/placeholder/ContainsAsserter.java, chutney/action-impl/src/main/java/com/chutneytesting/action/assertion/placeholder/EqualDateAsserter.java, chutney/action-impl/src/main/java/com/chutneytesting/action/assertion/placeholder/GreaterThanAsserter.java, chutney/action-impl/src/main/java/com/chutneytesting/action/assertion/placeholder/GuardedPlaceholderAsserter.java, chutney/action-impl/src/main/java/com/chutneytesting/action/assertion/placeholder/IsEmptyAsserter.java, chutney/action-impl/src/main/java/com/chutneytesting/action/assertion/placeholder/LenientEqualAsserter.java, chutney/action-impl/src/main/java/com/chutneytesting/action/assertion/placeholder/LessThanAsserter.java, chutney/action-impl/src/main/java/com/chutneytesting/action/assertion/placeholder/MatchesStringAsserter.java, chutney/action-impl/src/main/java/com/chutneytesting/action/assertion/placeholder/PlaceholderAsserterUtils.java, chutney/action-impl/src/main/java/com/chutneytesting/action/common/JsonUtils.java, chutney/action-impl/src/test/java/com/chutneytesting/action/assertion/JsonAssertActionTest.java, chutney/action-impl/src/test/java/com/chutneytesting/action/assertion/XmlAssertActionTest.java
=> XML asserts : guard against null value for placeholder asserts and soft assert for multiple expectations

chutney/ui/src/app/modules/campaign/components/campaign-list/campaign-list.component.html, chutney/ui/src/app/modules/campaign/components/execution/detail/campaign-execution.component.html, chutney/ui/src/app/modules/campaign/components/execution/history/list/campaign-executions.component.html, chutney/ui/src/app/modules/dataset/components/dataset-list/dataset-list.component.html, chutney/ui/src/app/modules/environment-variable/list/environments-variables.component.html, chutney/ui/src/app/modules/environment/list/environments.component.html, chutney/ui/src/app/modules/execution-search/components/resultExecutionSearchList/execution-search-list.component.html, chutney/ui/src/app/modules/scenarios/components/execution/history/list/scenario-executions.component.html, chutney/ui/src/app/modules/scenarios/components/search-list/scenarios.component.html, chutney/ui/src/app/modules/target/details/target.component.html, chutney/ui/src/app/modules/target/list/targets.component.html, chutney/ui/src/app/molecules/dialog/delete-confirm-dialog/confirm-dialog.component.html, chutney/ui/src/app/shared/components/layout/header/chutney-main-header.component.html, chutney/ui/src/app/shared/components/layout/left-menu/chutney-left-menu.component.html, chutney/ui/src/app/shared/components/layout/right-menu/chutney-right-menu.component.html
=> Clean Bootstrap Tooltip usage

acceptance-tests/pom.xml, chutney/action-impl/pom.xml, chutney/action-spi/pom.xml, chutney/engine/pom.xml, chutney/environment/pom.xml, chutney/jira/pom.xml, chutney/packaging/local-api-unsecure/pom.xml, chutney/packaging/local-dev/pom.xml, chutney/packaging/pom.xml, chutney/pom.xml, chutney/server-core/pom.xml, chutney/server/pom.xml, chutney/tools/pom.xml, chutney/ui/pom.xml, example/pom.xml, idea-plugin/gradle.properties, kotlin-dsl/pom.xml, pom.xml
=> Prepare next development 3.1.1-SNAPSHOT

acceptance-tests/pom.xml, chutney/action-impl/pom.xml, chutney/action-spi/pom.xml, chutney/engine/pom.xml, chutney/environment/pom.xml, chutney/jira/pom.xml, chutney/packaging/local-api-unsecure/pom.xml, chutney/packaging/local-dev/pom.xml, chutney/packaging/pom.xml, chutney/pom.xml, chutney/server-core/pom.xml, chutney/server/pom.xml, chutney/tools/pom.xml, chutney/ui/pom.xml, example/pom.xml, idea-plugin/gradle.properties, kotlin-dsl/pom.xml, pom.xml
=> Prepare next development 3.1.2-SNAPSHOT

.idea/runConfigurations/install_local_api_unsecure_jar.xml, kotlin-dsl/src/main/kotlin/fr/enedis/chutney/kotlin/synchronize/EnvironmentSynchronizeService.kt, kotlin-dsl/src/test/kotlin/fr/enedis/chutney/kotlin/synchronize/EnvironmentServiceSynchronizationTest.kt
=> Fix package declaration in DSL

chutney/engine/src/main/java/fr/enedis/chutney/engine/domain/execution/engine/step/Step.java, chutney/engine/src/main/java/fr/enedis/chutney/engine/domain/execution/engine/step/StepState.java, chutney/engine/src/main/java/fr/enedis/chutney/engine/domain/execution/strategies/ForEachStrategy.java, chutney/engine/src/test/java/fr/enedis/chutney/engine/domain/execution/strategies/ForEachStrategyTest.java, chutney/engine/src/test/resources/scenarios_examples/forEachStrategy/iteration_with_retry.json, chutney/engine/src/test/resources/scenarios_examples/forEachStrategy/iteration_with_retry_with_dataset.json
=> Duplicate steps when retry + for strategy

chutney/ui/src/app/modules/scenarios/components/execution/sub/right-side-bar/scenario-execution-menu.component.ts, chutney/ui/src/app/shared/directives/hasAuthorization.directive.ts
=> Directive hasAuthorization to not re insert view

chutney/ui/src/app/core/services/sso.service.ts
fixes #181 
Ask for sso config on associated service instantiation.
=> SSO - Remove local storage if no config

chutney/ui/src/app/core/model/scenario/execution.model.ts, chutney/ui/src/app/modules/scenarios/components/execution/history/scenario-executions-history.component.ts
=> Refresh scenario executions when running ones exist

chutney/ui/src/app/modules/dataset/components/dataset-list/dataset-list.component.html, chutney/ui/src/app/modules/dataset/components/dataset-list/dataset-list.component.ts
=> Keep dataset filters on page reload

chutney/server/src/main/java/fr/enedis/chutney/campaign/domain/CampaignExecutionRepository.java, chutney/server/src/main/java/fr/enedis/chutney/campaign/infra/CampaignExecutionDBRepository.java, chutney/server/src/main/java/fr/enedis/chutney/campaign/infra/jpa/CampaignExecutionEntity.java, chutney/server/src/main/java/fr/enedis/chutney/dataset/infra/DatasetMapper.java, chutney/server/src/main/java/fr/enedis/chutney/execution/domain/campaign/CampaignExecutionEngine.java, chutney/server/src/main/java/fr/enedis/chutney/execution/infra/storage/jpa/ScenarioExecutionEntity.java, chutney/server/src/test/java/changelog/LiquibaseChangelogTest.java, chutney/server/src/test/java/fr/enedis/chutney/campaign/infra/FakeCampaignRepository.java, chutney/server/src/test/java/fr/enedis/chutney/campaign/infra/jpa/CampaignExecutionEntityTest.java, chutney/server/src/test/java/fr/enedis/chutney/execution/domain/campaign/CampaignExecutionEngineTest.java, chutney/ui/src/app/modules/campaign/components/campaign-list/campaign-list.component.html
fixes #188 
* Map custom dataset id to constant for campaign execution write
* Fix campaign execution engine to not find custom dataset for scenarios
* Refacto
=> Hande campaign execution custom dataset

CHANGELOG.md, acceptance-tests/pom.xml, chutney/action-impl/pom.xml, chutney/action-spi/pom.xml, chutney/engine/pom.xml, chutney/environment/pom.xml, chutney/jira/pom.xml, chutney/packaging/local-api-unsecure/pom.xml, chutney/packaging/local-dev/pom.xml, chutney/packaging/pom.xml, chutney/pom.xml, chutney/server-core/pom.xml, chutney/server/pom.xml, chutney/tools/pom.xml, chutney/ui/pom.xml, example/pom.xml, idea-plugin/gradle.properties, kotlin-dsl/pom.xml, pom.xml
=> chore(): Release 3.2.1

chutney/ui/src/app/shared/pipes/prettyPrint.pipe.spec.ts, chutney/ui/src/app/shared/pipes/prettyPrint.pipe.ts
Fix image and link rendering on report (input, output, variables,...)
create and execute this scenario:
```
{
givens:
[
{
description: Put xml in context
implementation:
{
type: context-put
inputs:
{
entries:
{
img: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIAXDIBKE0DHxgljNBAAO9TXL0Y4OHwAAAABJRU5ErkJggg==
link: data:application/json;base64,ewogICJuYW1lIjogIkFsaWNlIiwKICAiYWdlIjogMzAsCiAgImVtYWlsIjogImFsaWNlQGV4YW1wbGUuY29tIiwKICAiaXNfbWVtYmVyIjogdHJ1ZQp9
}
}
}
}
]
when: {}
}
```
=> fix(): fix img and link rendering on execution report

CHANGELOG.md, acceptance-tests/pom.xml, chutney/action-impl/pom.xml, chutney/action-spi/pom.xml, chutney/engine/pom.xml, chutney/environment/pom.xml, chutney/jira/pom.xml, chutney/packaging/local-api-unsecure/pom.xml, chutney/packaging/local-dev/pom.xml, chutney/packaging/pom.xml, chutney/pom.xml, chutney/server-core/pom.xml, chutney/server/pom.xml, chutney/tools/pom.xml, chutney/ui/pom.xml, example/pom.xml, idea-plugin/gradle.properties, kotlin-dsl/pom.xml, pom.xml
=> chore(): Release 3.2.2

acceptance-tests/pom.xml, chutney/action-impl/pom.xml, chutney/action-spi/pom.xml, chutney/engine/pom.xml, chutney/environment/pom.xml, chutney/jira/pom.xml, chutney/packaging/local-api-unsecure/pom.xml, chutney/packaging/local-dev/pom.xml, chutney/packaging/pom.xml, chutney/pom.xml, chutney/server-core/pom.xml, chutney/server/pom.xml, chutney/tools/pom.xml, chutney/ui/pom.xml, example/pom.xml, idea-plugin/gradle.properties, kotlin-dsl/pom.xml, pom.xml
=> chore(): Prepare next development version 3.2.3-SNAPSHOT

acceptance-tests/pom.xml, chutney/action-impl/pom.xml, chutney/action-spi/pom.xml, chutney/engine/pom.xml, chutney/environment/pom.xml, chutney/jira/pom.xml, chutney/packaging/local-api-unsecure/pom.xml, chutney/packaging/local-dev/pom.xml, chutney/packaging/pom.xml, chutney/pom.xml, chutney/server-core/pom.xml, chutney/server/pom.xml, chutney/tools/pom.xml, chutney/ui/pom.xml, example/pom.xml, idea-plugin/gradle.properties, kotlin-dsl/pom.xml, pom.xml
=> chore: Prepare next development version 3.3.1-SNAPSHOT
